- name: Changes to installations
  hosts: remo
  become: yes
  tasks:
  - name: changing package states
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: "python", state: installed}
    - {name: "zip", state: "present"}
    - {name: "mysql", state: "absent"}


# /////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# - name: Python and zip installation
#   hosts: remo
#   become: yes
#   tasks: 
#   - name: task1
#     ansible.builtin.package:
#       name: "{{item}}"
#       state: installed
#     loop:
#     - python
#     - zip