- name: Play1
  hosts: remo
  become: yes
  connection: local
  tasks:
  - name: install netaddr
    ansible.builtin.package:
      name: netaddr
      state: installed

  - name: undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Steve') }}"

  - name: string to list
    vars:
      courses: "AWS, Ansible, Terraform"
    ansible.builtin.debug:
      msg: "Courses are:{{courses | split(',')}}"
  - name: list to string
    vars:
      courses: 
      - AWS
      - Ansible
      - Terraform
    ansible.builtin.debug:
      msg: "Courses are:{{courses | join(', ')}}"
  - name: map to list
    vars:
      courses: 
        ci: 'jenkins'
        IaC: 'Ansible'
        Cloud: 'AWS'
    ansible.builtin.debug:
      msg: "Courses are:{{courses | dict2items}}"
  - name: list to map
    vars:
      courses:
      - { 'key': 'ci', 'value': 'jenkins' }
      - { 'key': 'IaC', 'value': 'Ansible' }
      - { 'key': 'Cloud', 'value': 'AWS' }
    ansible.builtin.debug:
      msg: "Courses are {{courses | items2dict}}"

  - name: minimum number
    vars:
      numbers: [34,54,65,7,23,41]
    ansible.builtin.debug:
      msg: "Min number is: {{numbers | min}}"

  - name: maximum number
    vars:
      numbers: [34,54,65,7,23,41]
    ansible.builtin.debug:
      msg: "Min number is: {{numbers | max}}"

  - name: convert to upper
    vars:
      Name: Steve jobs
    ansible.builtin.debug:
      msg: "Name in upper case: {{Name | upper}}"

  - name: convert to lower
    vars:
      Name: Steve jobs
    ansible.builtin.debug:
      msg: "Name in lower case: {{Name | lower}}"

  - name: Checking the ip address is valid or not
    vars: 
      ip: "45.23.12.43"
    ansible.builtin.debug:
      msg: "ip address {{ip | ansible.utils.ipaddr}}"