- name: Play1
  hosts: remo
  connection: local
  tasks:
  - name: undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Sri') }}"

  - name: string to list
    vars:
      courses: "AWS, Ansible, Terraform"
    ansible.builtin.debug:
      msg: "Courses are:{{courses | split(',')}}"
