- name: Shell and command module testing
  hosts: remo
  connection: local
  tasks:
  - name: Shell testing
    ansible.builtin.shell: ls -ltr > /tmp/test1.txt
    register: shell_result
  - name: printing shell result
    ansible.builtin.debug:
      msg: "Result is: {{shell_result}}"