- name: Backend setup
  hosts: backend
  become: yes
  tasks:
  - name: disable and enable nodejs
    ansible.builtin.service:
      name: nodejs:20
      enabled:yes
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present